/**
 * Post-restart wake steer — the deterministic block itself: the state-label
 * mapping and the pure builder for the context block prepended to a
 * restarted thread's next user turn (see t3team-restartWakeSteer.ts for the
 * loader that decides WHEN it applies).
 *
 * @module t3team-restartWakeSteerBlock
 */
import { type OrchestrationThreadShell } from "@t3tools/contracts";
import { deriveThreadRunState } from "@t3tools/shared/t3team-threadRunStatus";

/** Cap the child listing in the steer: keep the block cheap for large fleets. */
export const RESTART_WAKE_STEER_CHILD_CAP = 20;

/** One child line in the steer, from persisted shell data only. */
export interface RestartWakeSteerChild {
  readonly threadId: string;
  readonly title: string;
  readonly state: string;
  readonly lastActivityAt: string;
  readonly branch: string | null;
  readonly worktreePath: string | null;
}

/**
 * Map a child shell onto its steer state label. The restart marker on the
 * child's OWN session (the same durable fact as the parent's, written by the
 * startup reconcile) labels a terminal child "stopped on restart";
 * completed/idle/waiting fold to "idle" — the steer asks "is it live?".
 */
export function childSteerState(shell: OrchestrationThreadShell): string {
  if (shell.settledOverride === "settled") return "settled";
  const state = deriveThreadRunState({
    session: shell.session,
    latestTurn: shell.latestTurn,
    ...(shell.backgroundLiveness !== undefined
      ? { backgroundLiveness: shell.backgroundLiveness }
      : {}),
  });
  const restarted = shell.session?.stoppedByServerRestart === true;
  if ((state === "failed" || state === "aborted") && restarted) return "stopped on restart";
  if (state === "completed" || state === "idle" || state === "waiting") return "idle";
  return state === "aborted" ? "stopped" : state;
}

/** Build the steer block from preloaded child rows. Pure, deterministic. */
export function buildRestartWakeSteer(input: {
  readonly children: ReadonlyArray<RestartWakeSteerChild>;
  readonly omittedCount: number;
}): string {
  const lines: string[] = [
    "[Server restart notice — generated by the server, not a user message]",
    "The server restarted while your last turn was in flight; that turn was interrupted mid-work.",
  ];
  if (input.children.length > 0) {
    lines.push("Child thread state:");
    for (const child of input.children) {
      let line =
        `- «${child.title}» (thread ${child.threadId}) — ${child.state} ` +
        `— last activity ${child.lastActivityAt}`;
      if (child.branch !== null) line += ` — branch: ${child.branch}`;
      if (child.worktreePath !== null) line += ` — worktree: ${child.worktreePath}`;
      lines.push(line);
    }
  } else {
    lines.push("No child threads are recorded for this thread.");
  }
  if (input.omittedCount > 0) {
    lines.push(
      `+ ${input.omittedCount} more child thread(s) — list them with t3team_children op:list.`,
    );
  }
  lines.push("");
  lines.push(
    "The server restarted mid-work. If you have child threads, check their state " +
      "(t3team_children op:status / op:list) and continue where you left off.",
  );
  return lines.join("\n");
}
