// @effect-diagnostics nodeBuiltinImport:off - builds a temp repository with a bare origin.
import * as NodePath from "node:path";

import * as NodeServices from "@effect/platform-node/NodeServices";
import { it } from "@effect/vitest";
import { ProjectId, SourceControlProviderError } from "@t3tools/contracts";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Layer from "effect/Layer";
import { expect } from "vite-plus/test";

import * as ServerConfig from "./config.ts";
import * as GitManager from "./git/GitManager.ts";
import * as T3TeamChangeRequestPublisher from "./t3team-changeRequestPublisher.ts";
import {
  type ChangeRequestPublishInput,
  describeChangeRequestPublishError,
} from "./t3team-changeRequestPublishErrors.ts";
import * as GitVcsDriver from "./vcs/GitVcsDriver.ts";
import * as VcsProcess from "./vcs/VcsProcess.ts";
import * as WorkspacePaths from "./workspace/WorkspacePaths.ts";

const layerGit = GitVcsDriver.layer.pipe(
  Layer.provide(ServerConfig.layerTest(process.cwd(), { prefix: "t3team-cr-publish-test-" })),
  Layer.provideMerge(VcsProcess.layer),
  Layer.provideMerge(NodeServices.layer),
);

const git = (cwd: string, args: ReadonlyArray<string>) =>
  GitVcsDriver.GitVcsDriver.pipe(
    Effect.flatMap((driver) => driver.execute({ operation: "test.git", cwd, args })),
    Effect.map((result) => result.stdout.trim()),
  );

/** A repository on `main` with one commit and a bare `origin` holding it. */
const makeRepo = Effect.gen(function* () {
  const fs = yield* FileSystem.FileSystem;
  const repo = yield* fs.makeTempDirectoryScoped({ prefix: "t3team-cr-repo-" });
  const origin = yield* fs.makeTempDirectoryScoped({ prefix: "t3team-cr-origin-" });
  yield* git(origin, ["init", "--bare"]);
  yield* git(repo, ["init", "--initial-branch=main"]);
  yield* git(repo, ["config", "user.email", "test@example.com"]);
  yield* git(repo, ["config", "user.name", "Test User"]);
  yield* fs.writeFileString(NodePath.join(repo, "README.md"), "hello\n");
  yield* git(repo, ["add", "README.md"]);
  yield* git(repo, ["commit", "-m", "Initial commit"]);
  yield* git(repo, ["remote", "add", "origin", origin]);
  yield* git(repo, ["push", "-u", "origin", "main"]);
  const write = (file: string, text: string) =>
    fs
      .makeDirectory(NodePath.dirname(NodePath.join(repo, file)), { recursive: true })
      .pipe(Effect.andThen(fs.writeFileString(NodePath.join(repo, file), text)));
  return { repo, write };
});

/** The publisher over the real git driver; the host side is a recording `openChangeRequest`. */
const makePublisher = (hostFailure?: SourceControlProviderError) =>
  Effect.gen(function* () {
    const opened: Array<GitManager.GitOpenChangeRequestInput> = [];
    const publisher = yield* T3TeamChangeRequestPublisher.T3TeamChangeRequestPublisher.pipe(
      Effect.provide(
        T3TeamChangeRequestPublisher.layer.pipe(
          Layer.provide(WorkspacePaths.layer),
          Layer.provide(
            Layer.mock(GitManager.GitManager)({
              openChangeRequest: (input) =>
                hostFailure !== undefined
                  ? Effect.fail(hostFailure)
                  : Effect.sync(() => {
                      opened.push(input);
                      return {
                        status:
                          opened.length === 1 ? ("created" as const) : ("opened_existing" as const),
                        provider: "github" as const,
                        repository: "acme/widgets",
                        url: "https://github.com/acme/widgets/pull/7",
                        number: 7,
                        baseBranch: input.baseBranch ?? "main",
                        headBranch: input.branch,
                      };
                    }),
            }),
          ),
        ),
      ),
    );
    return { publisher, opened };
  });

const projectId = ProjectId.make("project-1");

const publishInput = (cwd: string, overrides: Partial<ChangeRequestPublishInput> = {}) => ({
  cwd,
  projectId,
  branch: "machine/setup",
  paths: [".devcontainer/devcontainer.json"],
  commitMessage: "chore: add machine setup\n\nGenerated by the setup recipe.",
  title: "Add machine setup",
  body: "Adds the dev container.",
  ...overrides,
});

it.layer(layerGit)("T3TeamChangeRequestPublisher", (it) => {
  it.effect("commits only the listed paths, pushes the branch, and opens the change request", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher, opened } = yield* makePublisher();
      yield* write(".devcontainer/devcontainer.json", "{}\n");
      yield* write("notes.txt", "not for publishing\n");

      const result = yield* publisher.publish(publishInput(repo, { draft: true }));

      expect(result).toMatchObject({
        url: "https://github.com/acme/widgets/pull/7",
        number: 7,
        repository: "acme/widgets",
        provider: "github",
        branch: "machine/setup",
        projectId,
      });
      expect(yield* git(repo, ["branch", "--show-current"])).toBe("machine/setup");
      expect(yield* git(repo, ["show", "--name-only", "--format=%s", "HEAD"])).toBe(
        "chore: add machine setup\n\n.devcontainer/devcontainer.json",
      );
      expect(yield* git(repo, ["status", "--porcelain"])).toBe("?? notes.txt");
      expect(yield* git(repo, ["ls-remote", "origin", "refs/heads/machine/setup"])).toContain(
        result.commit,
      );
      expect(opened).toEqual([
        {
          cwd: yield* git(repo, ["rev-parse", "--show-toplevel"]),
          branch: "machine/setup",
          baseBranch: undefined,
          title: "Add machine setup",
          body: "Adds the dev container.",
          draft: true,
        },
      ]);
    }),
  );

  it.effect("a re-run with nothing new pushes and returns the open change request", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher, opened } = yield* makePublisher();
      yield* write(".devcontainer/devcontainer.json", "{}\n");

      const first = yield* publisher.publish(publishInput(repo));
      const second = yield* publisher.publish(publishInput(repo));

      expect(second).toEqual(first);
      expect(yield* git(repo, ["rev-list", "--count", "HEAD"])).toBe("2");
      expect(opened).toHaveLength(2);
    }),
  );

  it.effect("refuses empty, absolute, '..', .git and outside-the-root paths before git runs", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher, opened } = yield* makePublisher();
      yield* write(".devcontainer/devcontainer.json", "{}\n");
      const refusals: Array<[ReadonlyArray<string>, string]> = [
        [[], "list at least one repository-relative path"],
        [["/etc/passwd"], "must be relative to the project root"],
        [["a/../.devcontainer/devcontainer.json"], "contains '..'"],
        [["../outside.txt"], "contains '..'"],
        [[".git/config"], "is inside .git"],
        [["."], "must be relative to the project root"],
        [["missing.txt"], "did not match any files"],
      ];

      for (const [paths, expected] of refusals) {
        const error = yield* Effect.flip(publisher.publish(publishInput(repo, { paths })));
        expect(describeChangeRequestPublishError(error)).toContain(expected);
      }
      expect(yield* git(repo, ["branch", "--show-current"])).toBe("main");
      expect(opened).toEqual([]);
    }),
  );

  it.effect("nothing to commit on a new branch is refused and leaves the checkout on main", () =>
    Effect.gen(function* () {
      const { repo } = yield* makeRepo;
      const { publisher } = yield* makePublisher();

      const error = yield* Effect.flip(
        publisher.publish(publishInput(repo, { paths: ["README.md"] })),
      );

      expect(error._tag).toBe("ChangeRequestNothingToCommitError");
      expect(describeChangeRequestPublishError(error)).toContain("Nothing to commit");
      expect(yield* git(repo, ["branch", "--list", "machine/setup"])).toBe("");
    }),
  );

  it.effect("an existing branch with diverging history is refused", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher } = yield* makePublisher();
      yield* git(repo, ["checkout", "-b", "machine/setup"]);
      yield* git(repo, ["commit", "--allow-empty", "-m", "elsewhere"]);
      yield* git(repo, ["checkout", "main"]);
      yield* write(".devcontainer/devcontainer.json", "{}\n");

      const error = yield* Effect.flip(publisher.publish(publishInput(repo)));

      expect(error._tag).toBe("ChangeRequestBranchDivergedError");
      expect(yield* git(repo, ["branch", "--show-current"])).toBe("main");
    }),
  );

  it.effect("a push without credentials says the user is not signed in", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher, opened } = yield* makePublisher();
      // An ssh remote whose transport refuses the key, the way ssh reports it; nothing leaves the host.
      yield* git(repo, [
        "remote",
        "set-url",
        "--push",
        "origin",
        "git@example.invalid:acme/widgets.git",
      ]);
      yield* git(repo, [
        "config",
        "core.sshCommand",
        "sh -c 'echo \"git@example.invalid: Permission denied (publickey).\" >&2; exit 255'",
      ]);
      yield* write(".devcontainer/devcontainer.json", "{}\n");

      const error = yield* Effect.flip(publisher.publish(publishInput(repo)));

      expect(error._tag).toBe("ChangeRequestNotSignedInError");
      expect(describeChangeRequestPublishError(error)).toMatch(
        /^Not signed in: could not push the branch to origin\. /u,
      );
      expect(opened).toEqual([]);
    }),
  );

  it.effect("a host that refuses the credential says the user is not signed in to it", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const detail = "GitHub CLI is not authenticated. Run `gh auth login` and retry.";
      const { publisher } = yield* makePublisher(
        new SourceControlProviderError({
          provider: "github",
          operation: "createChangeRequest",
          cwd: repo,
          detail,
          cause: { _tag: "GitHubCliAuthenticationError" },
        }),
      );
      yield* write(".devcontainer/devcontainer.json", "{}\n");

      const error = yield* Effect.flip(publisher.publish(publishInput(repo)));

      expect(describeChangeRequestPublishError(error)).toBe(
        `Not signed in: could not open the change request on github. ${detail}`,
      );
    }),
  );

  it.effect("a push the remote rejects is reported with what git said", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher, opened } = yield* makePublisher();
      // origin already holds machine/setup at a commit the local branch will not contain.
      yield* git(repo, ["commit", "--allow-empty", "-m", "remote only"]);
      yield* git(repo, ["push", "origin", "HEAD:refs/heads/machine/setup"]);
      yield* git(repo, ["reset", "--hard", "HEAD~1"]);
      yield* write(".devcontainer/devcontainer.json", "{}\n");

      const error = yield* Effect.flip(publisher.publish(publishInput(repo)));

      expect(error._tag).toBe("ChangeRequestPushRejectedError");
      expect(describeChangeRequestPublishError(error)).toMatch(
        /^Pushing 'machine\/setup' to origin was rejected\. .*rejected/su,
      );
      expect(opened).toEqual([]);
    }),
  );
});
