// @effect-diagnostics nodeBuiltinImport:off - builds a temp repository with a bare origin.
import * as NodeChildProcess from "node:child_process";
import * as NodePath from "node:path";

import * as NodeServices from "@effect/platform-node/NodeServices";
import { it } from "@effect/vitest";
import { ProjectId, SourceControlProviderError } from "@t3tools/contracts";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Layer from "effect/Layer";
import { expect } from "vite-plus/test";

import * as ServerConfig from "./config.ts";
import * as GitManager from "./git/GitManager.ts";
import * as T3TeamChangeRequestPublisher from "./t3team-changeRequestPublisher.ts";
import {
  type ChangeRequestPublishInput,
  describeChangeRequestPublishError,
} from "./t3team-changeRequestPublishErrors.ts";
import * as GitVcsDriver from "./vcs/GitVcsDriver.ts";
import * as VcsProcess from "./vcs/VcsProcess.ts";
import * as WorkspacePaths from "./workspace/WorkspacePaths.ts";

const layerGit = GitVcsDriver.layer.pipe(
  Layer.provide(ServerConfig.layerTest(process.cwd(), { prefix: "t3team-cr-publish-test-" })),
  Layer.provideMerge(VcsProcess.layer),
  Layer.provideMerge(NodeServices.layer),
);

const git = (cwd: string, args: ReadonlyArray<string>) =>
  GitVcsDriver.GitVcsDriver.pipe(
    Effect.flatMap((driver) => driver.execute({ operation: "test.git", cwd, args })),
    Effect.map((result) => result.stdout.trim()),
  );

/** A repository on `main` with one commit and a bare `origin` holding it. */
const makeRepo = Effect.gen(function* () {
  const fs = yield* FileSystem.FileSystem;
  const repo = yield* fs.makeTempDirectoryScoped({ prefix: "t3team-cr-repo-" });
  const origin = yield* fs.makeTempDirectoryScoped({ prefix: "t3team-cr-origin-" });
  yield* git(origin, ["init", "--bare"]);
  yield* git(repo, ["init", "--initial-branch=main"]);
  yield* git(repo, ["config", "user.email", "test@example.com"]);
  yield* git(repo, ["config", "user.name", "Test User"]);
  yield* fs.writeFileString(NodePath.join(repo, "README.md"), "hello\n");
  yield* git(repo, ["add", "README.md"]);
  yield* git(repo, ["commit", "-m", "Initial commit"]);
  yield* git(repo, ["remote", "add", "origin", origin]);
  yield* git(repo, ["push", "-u", "origin", "main"]);
  const write = (file: string, text: string) =>
    fs
      .makeDirectory(NodePath.dirname(NodePath.join(repo, file)), { recursive: true })
      .pipe(Effect.andThen(fs.writeFileString(NodePath.join(repo, file), text)));
  return { repo, write };
});

/** The publisher over the real git driver; the host side is a recording `openChangeRequest`. */
const makePublisher = (hostFailure?: SourceControlProviderError) =>
  Effect.gen(function* () {
    const opened: Array<GitManager.GitOpenChangeRequestInput> = [];
    const publisher = yield* T3TeamChangeRequestPublisher.T3TeamChangeRequestPublisher.pipe(
      Effect.provide(
        T3TeamChangeRequestPublisher.layer.pipe(
          Layer.provide(WorkspacePaths.layer),
          Layer.provide(
            Layer.mock(GitManager.GitManager)({
              openChangeRequest: (input) =>
                hostFailure !== undefined
                  ? Effect.fail(hostFailure)
                  : Effect.sync(() => {
                      opened.push(input);
                      return {
                        status:
                          opened.length === 1 ? ("created" as const) : ("opened_existing" as const),
                        provider: "github" as const,
                        repository: "acme/widgets",
                        url: "https://github.com/acme/widgets/pull/7",
                        number: 7,
                        baseBranch: input.baseBranch ?? "main",
                        headBranch: input.branch,
                      };
                    }),
            }),
          ),
        ),
      ),
    );
    return { publisher, opened };
  });

const projectId = ProjectId.make("project-1");

const publishInput = (cwd: string, overrides: Partial<ChangeRequestPublishInput> = {}) => ({
  cwd,
  projectId,
  branch: "machine/setup",
  paths: [".devcontainer/devcontainer.json"],
  commitMessage: "chore: add machine setup\n\nGenerated by the setup recipe.",
  title: "Add machine setup",
  body: "Adds the dev container.",
  ...overrides,
});

it.layer(layerGit)("T3TeamChangeRequestPublisher", (it) => {
  it.effect("commits only the listed paths, pushes the branch, and opens the change request", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher, opened } = yield* makePublisher();
      yield* write(".devcontainer/devcontainer.json", "{}\n");
      yield* write("notes.txt", "not for publishing\n");

      const result = yield* publisher.publish(publishInput(repo, { draft: true }));

      expect(result).toMatchObject({
        url: "https://github.com/acme/widgets/pull/7",
        number: 7,
        repository: "acme/widgets",
        provider: "github",
        branch: "machine/setup",
        projectId,
      });
      expect(yield* git(repo, ["branch", "--show-current"])).toBe("main");
      expect(yield* git(repo, ["show", "--name-only", "--format=%s", "machine/setup"])).toBe(
        "chore: add machine setup\n\n.devcontainer/devcontainer.json",
      );
      expect(yield* git(repo, ["rev-parse", "machine/setup~1"])).toBe(
        yield* git(repo, ["rev-parse", "main"]),
      );
      expect(yield* git(repo, ["ls-remote", "origin", "refs/heads/machine/setup"])).toContain(
        result.commit,
      );
      expect(opened).toEqual([
        {
          cwd: yield* git(repo, ["rev-parse", "--show-toplevel"]),
          branch: "machine/setup",
          baseBranch: undefined,
          title: "Add machine setup",
          body: "Adds the dev container.",
          draft: true,
        },
      ]);
    }),
  );

  it.effect("a re-run with nothing new pushes and returns the open change request", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher, opened } = yield* makePublisher();
      yield* write(".devcontainer/devcontainer.json", "{}\n");

      const first = yield* publisher.publish(publishInput(repo));
      const second = yield* publisher.publish(publishInput(repo));

      expect(second).toEqual(first);
      expect(yield* git(repo, ["rev-list", "--count", "machine/setup"])).toBe("2");
      expect(opened).toHaveLength(2);
    }),
  );

  it.effect("refuses empty, absolute, '..', .git and outside-the-root paths before git runs", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher, opened } = yield* makePublisher();
      yield* write(".devcontainer/devcontainer.json", "{}\n");
      const refusals: Array<[ReadonlyArray<string>, string]> = [
        [[], "list at least one repository-relative path"],
        [["/etc/passwd"], "must be relative to the project root"],
        [["a/../.devcontainer/devcontainer.json"], "contains '..'"],
        [["../outside.txt"], "contains '..'"],
        [[".git/config"], "is inside .git"],
        [["."], "must be relative to the project root"],
        [["missing.txt"], "did not match any files"],
      ];

      for (const [paths, expected] of refusals) {
        const error = yield* Effect.flip(publisher.publish(publishInput(repo, { paths })));
        expect(describeChangeRequestPublishError(error)).toContain(expected);
      }
      expect(yield* git(repo, ["branch", "--show-current"])).toBe("main");
      expect(opened).toEqual([]);
    }),
  );

  it.effect("nothing to commit on a new branch is refused and leaves the checkout on main", () =>
    Effect.gen(function* () {
      const { repo } = yield* makeRepo;
      const { publisher } = yield* makePublisher();

      const error = yield* Effect.flip(
        publisher.publish(publishInput(repo, { paths: ["README.md"] })),
      );

      expect(error._tag).toBe("ChangeRequestNothingToCommitError");
      expect(describeChangeRequestPublishError(error)).toContain("Nothing to commit");
      expect(yield* git(repo, ["branch", "--list", "machine/setup"])).toBe("");
    }),
  );

  it.effect("leaves the checkout's branch, staged work and other changes as they were", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher } = yield* makePublisher();
      yield* write("feature.ts", "export const x = 1;\n");
      yield* git(repo, ["add", "feature.ts"]);
      yield* write("README.md", "hello, edited\n");
      yield* write(".devcontainer/devcontainer.json", "{}\n");
      const before = yield* git(repo, ["status", "--porcelain"]);

      yield* publisher.publish(publishInput(repo));

      expect(yield* git(repo, ["branch", "--show-current"])).toBe("main");
      expect(yield* git(repo, ["status", "--porcelain"])).toBe(before);
      expect(yield* git(repo, ["show", "--name-only", "--format=", "machine/setup"])).toBe(
        ".devcontainer/devcontainer.json",
      );
    }),
  );

  it.effect("an update after the checkout moved on lands on the change request's branch", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher } = yield* makePublisher();
      yield* write(".devcontainer/devcontainer.json", "{}\n");
      const first = yield* publisher.publish(publishInput(repo));
      yield* git(repo, ["commit", "--allow-empty", "-m", "the user's own work"]);
      yield* write(".devcontainer/devcontainer.json", '{ "image": "node" }\n');

      const second = yield* publisher.publish(publishInput(repo));

      expect(yield* git(repo, ["rev-parse", "machine/setup~1"])).toBe(first.commit);
      expect(yield* git(repo, ["log", "--format=%s", "machine/setup"])).not.toContain(
        "the user's own work",
      );
      expect(yield* git(repo, ["ls-remote", "origin", "refs/heads/machine/setup"])).toContain(
        second.commit,
      );
    }),
  );

  it.effect("continues a branch only the remote has, instead of replacing it", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher } = yield* makePublisher();
      yield* write(".devcontainer/devcontainer.json", "{}\n");
      const first = yield* publisher.publish(publishInput(repo));
      yield* git(repo, ["branch", "-D", "machine/setup"]);
      yield* write(".devcontainer/devcontainer.json", '{ "image": "node" }\n');

      yield* publisher.publish(publishInput(repo));

      expect(yield* git(repo, ["rev-parse", "machine/setup~1"])).toBe(first.commit);
    }),
  );

  it.effect("on the branch itself, the committed paths do not read as staged afterwards", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher } = yield* makePublisher();
      yield* git(repo, ["checkout", "-b", "machine/setup"]);
      yield* write(".devcontainer/devcontainer.json", "{}\n");

      const result = yield* publisher.publish(publishInput(repo));

      expect(yield* git(repo, ["rev-parse", "HEAD"])).toBe(result.commit);
      expect(yield* git(repo, ["status", "--porcelain"])).toBe("");
    }),
  );

  it.effect("refuses a branch checked out in another worktree, and leaves it where it was", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher, opened } = yield* makePublisher();
      const fs = yield* FileSystem.FileSystem;
      const other = NodePath.join(yield* fs.makeTempDirectoryScoped(), "other");
      yield* git(repo, ["worktree", "add", "-b", "machine/setup", other]);
      const before = yield* git(repo, ["rev-parse", "machine/setup"]);
      yield* write(".devcontainer/devcontainer.json", "{}\n");

      const error = yield* Effect.flip(publisher.publish(publishInput(repo)));

      expect(error._tag).toBe("ChangeRequestBranchBusyError");
      expect(describeChangeRequestPublishError(error)).toContain("checked out in the worktree");
      expect(yield* git(repo, ["rev-parse", "machine/setup"])).toBe(before);
      expect(opened).toEqual([]);
    }),
  );

  it.effect("refuses the checkout's own branch while a merge is in progress on it", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher } = yield* makePublisher();
      yield* git(repo, ["checkout", "-b", "side"]);
      yield* write("README.md", "side\n");
      yield* git(repo, ["commit", "-am", "side"]);
      yield* git(repo, ["checkout", "-b", "machine/setup", "main"]);
      yield* write("README.md", "mine\n");
      yield* git(repo, ["commit", "-am", "mine"]);
      yield* GitVcsDriver.GitVcsDriver.pipe(
        Effect.flatMap((driver) =>
          driver.execute({
            operation: "test.git",
            cwd: repo,
            args: ["merge", "side"],
            allowNonZeroExit: true,
          }),
        ),
      );
      yield* write(".devcontainer/devcontainer.json", "{}\n");

      const error = yield* Effect.flip(publisher.publish(publishInput(repo)));

      expect(error._tag).toBe("ChangeRequestBranchBusyError");
      expect(describeChangeRequestPublishError(error)).toContain("a merge in progress");
    }),
  );

  it.effect("refuses a branch another worktree is rebasing, though git lists it as detached", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher } = yield* makePublisher();
      const fs = yield* FileSystem.FileSystem;
      const other = NodePath.join(yield* fs.makeTempDirectoryScoped(), "other");
      yield* write("README.md", "main\n");
      yield* git(repo, ["commit", "-am", "main moves"]);
      yield* git(repo, ["worktree", "add", "-b", "machine/setup", other, "HEAD~1"]);
      yield* fs.writeFileString(NodePath.join(other, "README.md"), "theirs\n");
      yield* git(other, ["commit", "-am", "theirs"]);
      yield* GitVcsDriver.GitVcsDriver.pipe(
        Effect.flatMap((driver) =>
          driver.execute({
            operation: "test.git",
            cwd: other,
            args: ["rebase", "main"],
            allowNonZeroExit: true,
          }),
        ),
      );
      const before = yield* git(repo, ["rev-parse", "machine/setup"]);
      yield* write(".devcontainer/devcontainer.json", "{}\n");

      const error = yield* Effect.flip(publisher.publish(publishInput(repo)));

      expect(describeChangeRequestPublishError(error)).toContain("is rebasing it");
      expect(yield* git(repo, ["rev-parse", "machine/setup"])).toBe(before);
    }),
  );

  it.effect("a remote that cannot be read is reported, and no local branch is invented", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher } = yield* makePublisher();
      yield* git(repo, ["remote", "set-url", "origin", NodePath.join(repo, "no-such-origin")]);
      yield* write(".devcontainer/devcontainer.json", "{}\n");

      const error = yield* Effect.flip(publisher.publish(publishInput(repo)));

      expect(error._tag).toBe("ChangeRequestRemoteUnreadableError");
      expect(yield* git(repo, ["branch", "--list", "machine/setup"])).toBe("");
    }),
  );

  it.effect("signs the commit when the user's config signs commits", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher } = yield* makePublisher();
      const fs = yield* FileSystem.FileSystem;
      const key = NodePath.join(yield* fs.makeTempDirectoryScoped(), "key");
      yield* Effect.promise(
        () =>
          new Promise<void>((resolve, reject) =>
            NodeChildProcess.execFile(
              "ssh-keygen",
              ["-q", "-t", "ed25519", "-N", "", "-f", key],
              (error) => (error ? reject(error) : resolve()),
            ),
          ),
      );
      yield* git(repo, ["config", "gpg.format", "ssh"]);
      yield* git(repo, ["config", "user.signingkey", `${key}.pub`]);
      yield* git(repo, ["config", "commit.gpgsign", "true"]);
      yield* write(".devcontainer/devcontainer.json", "{}\n");

      yield* publisher.publish(publishInput(repo));

      expect(yield* git(repo, ["cat-file", "commit", "machine/setup"])).toContain("gpgsig");
    }),
  );

  it.effect("a push without credentials says the user is not signed in", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher, opened } = yield* makePublisher();
      // An ssh remote whose transport refuses the key, the way ssh reports it; nothing leaves the host.
      yield* git(repo, [
        "remote",
        "set-url",
        "--push",
        "origin",
        "git@example.invalid:acme/widgets.git",
      ]);
      yield* git(repo, [
        "config",
        "core.sshCommand",
        "sh -c 'echo \"git@example.invalid: Permission denied (publickey).\" >&2; exit 255'",
      ]);
      yield* write(".devcontainer/devcontainer.json", "{}\n");

      const error = yield* Effect.flip(publisher.publish(publishInput(repo)));

      expect(error._tag).toBe("ChangeRequestNotSignedInError");
      expect(describeChangeRequestPublishError(error)).toMatch(
        /^Not signed in: could not push the branch to origin\. /u,
      );
      expect(opened).toEqual([]);
    }),
  );

  it.effect("a host that refuses the credential says the user is not signed in to it", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const detail = "GitHub CLI is not authenticated. Run `gh auth login` and retry.";
      const { publisher } = yield* makePublisher(
        new SourceControlProviderError({
          provider: "github",
          operation: "createChangeRequest",
          cwd: repo,
          detail,
          cause: { _tag: "GitHubCliAuthenticationError" },
        }),
      );
      yield* write(".devcontainer/devcontainer.json", "{}\n");

      const error = yield* Effect.flip(publisher.publish(publishInput(repo)));

      expect(describeChangeRequestPublishError(error)).toBe(
        `Not signed in: could not open the change request on github. ${detail}`,
      );
    }),
  );

  it.effect("a push the remote rejects is reported with what git said", () =>
    Effect.gen(function* () {
      const { repo, write } = yield* makeRepo;
      const { publisher, opened } = yield* makePublisher();
      // origin refuses every update, the way a protected-branch policy does.
      const fs = yield* FileSystem.FileSystem;
      const hook = NodePath.join(
        yield* git(repo, ["remote", "get-url", "origin"]),
        "hooks",
        "pre-receive",
      );
      yield* fs.writeFileString(hook, "#!/bin/sh\necho 'denied by policy' >&2\nexit 1\n");
      yield* fs.chmod(hook, 0o755);
      yield* write(".devcontainer/devcontainer.json", "{}\n");

      const error = yield* Effect.flip(publisher.publish(publishInput(repo)));

      expect(error._tag).toBe("ChangeRequestPushRejectedError");
      expect(describeChangeRequestPublishError(error)).toMatch(
        /^Pushing 'machine\/setup' to origin was rejected\. .*rejected/su,
      );
      expect(opened).toEqual([]);
    }),
  );
});
