/**
 * Deterministic tests for the post-restart wake steer (t3team-restartWakeSteer.ts):
 * the state-label mapping, the exact steer block text, the child cap, and the
 * loader's marker gate + failure degradation (no real timers/clocks involved —
 * the steer is built from persisted data only).
 */
import { ProjectId, ThreadId, type OrchestrationThreadShell } from "@t3tools/contracts";
import { assert, describe, expect, it } from "@effect/vitest";
import * as Effect from "effect/Effect";
import * as Option from "effect/Option";
import { PersistenceDecodeError } from "./persistence/Errors.ts";

import {
  RESTART_WAKE_STEER_CHILD_CAP,
  buildRestartWakeSteer,
  childSteerState,
  loadRestartWakeSteer,
} from "./t3team-restartWakeSteer.ts";

// Minimal shell factory: only the fields childSteerState reads matter.
const shell = (over: Record<string, unknown> = {}) =>
  ({
    id: ThreadId.make("shell-1"),
    projectId: ProjectId.make("project-1"),
    title: "Shell",
    branch: null,
    worktreePath: null,
    latestTurn: null,
    createdAt: "2026-09-15T10:00:00.000Z",
    updatedAt: "2026-09-15T18:00:00.000Z",
    settledOverride: null,
    settledAt: null,
    session: null,
    ...over,
  }) as unknown as OrchestrationThreadShell;

describe("childSteerState", () => {
  it("labels a restart-interrupted terminal child 'stopped on restart'", () => {
    expect(
      childSteerState(
        shell({
          session: {
            status: "error",
            lastError: "Restarted mid-turn — send a message to continue.",
            stoppedByServerRestart: true,
          },
        }),
      ),
    ).toBe("stopped on restart");
    expect(
      childSteerState(
        shell({
          session: {
            status: "stopped",
            lastError: null,
            stoppedByServerRestart: true,
          },
        }),
      ),
    ).toBe("stopped on restart");
  });

  it("keeps provider failures and user stops out of the restart label", () => {
    expect(
      childSteerState(shell({ session: { status: "error", lastError: "provider 502" } })),
    ).toBe("failed");
    expect(childSteerState(shell({ session: { status: "interrupted", lastError: null } }))).toBe(
      "stopped",
    );
  });

  it("folds completed/idle/waiting to 'idle' and passes running through", () => {
    expect(
      childSteerState(
        shell({
          session: { status: "ready", lastError: null },
          latestTurn: { state: "completed", turnId: "turn-1" },
        }),
      ),
    ).toBe("idle");
    expect(childSteerState(shell({ session: { status: "running", lastError: null } }))).toBe(
      "running",
    );
    expect(childSteerState(shell({ settledOverride: "settled" }))).toBe("settled");
  });
});

describe("buildRestartWakeSteer", () => {
  it("renders the exact deterministic block for children in mixed states", () => {
    const text = buildRestartWakeSteer({
      children: [
        {
          threadId: "child-a",
          title: "Build the installer",
          state: "stopped on restart",
          lastActivityAt: "2026-09-15T18:00:00.000Z",
          branch: "fix/installer",
          worktreePath: "/tmp/wt/fix-installer",
        },
        {
          threadId: "child-b",
          title: "Research the API",
          state: "running",
          lastActivityAt: "2026-09-15T18:05:00.000Z",
          branch: null,
          worktreePath: null,
        },
      ],
      omittedCount: 0,
    });
    assert.strictEqual(
      text,
      [
        "[Server restart notice — generated by the server, not a user message]",
        "The server restarted while your last turn was in flight; that turn was interrupted mid-work.",
        "Child thread state:",
        "- «Build the installer» (thread child-a) — stopped on restart — last activity 2026-09-15T18:00:00.000Z — branch: fix/installer — worktree: /tmp/wt/fix-installer",
        "- «Research the API» (thread child-b) — running — last activity 2026-09-15T18:05:00.000Z",
        "",
        "The server restarted mid-work. If you have child threads, check their state (t3team_children op:status / op:list) and continue where you left off.",
      ].join("\n"),
    );
  });

  it("notes an empty fleet and caps the listing", () => {
    const empty = buildRestartWakeSteer({ children: [], omittedCount: 0 });
    expect(empty).toContain("No child threads are recorded for this thread.");
    expect(empty).toContain(
      "The server restarted mid-work. If you have child threads, check their state",
    );

    const many = buildRestartWakeSteer({
      children: Array.from({ length: 5 }, (_, i) => ({
        threadId: `child-${i}`,
        title: `Child ${i}`,
        state: "idle",
        lastActivityAt: "2026-09-15T18:00:00.000Z",
        branch: null,
        worktreePath: null,
      })),
      omittedCount: 13,
    });
    expect(many).toContain("+ 13 more child thread(s) — list them with t3team_children op:list.");
    expect(many).not.toContain("child-23");
  });
});

describe("loadRestartWakeSteer", () => {
  const thread = {
    id: ThreadId.make("parent-1"),
    projectId: ProjectId.make("project-1"),
    session: { stoppedByServerRestart: true } as const,
  };

  it.effect("returns null without touching the query when the marker is absent", () =>
    Effect.gen(function* () {
      let queries = 0;
      const steer = yield* loadRestartWakeSteer({
        thread: { ...thread, session: null },
        query: {
          listChildThreadIdsByParent: () => Effect.sync(() => ++queries).pipe(Effect.as([])),
          getThreadShellById: () => Effect.succeed(Option.none()),
        },
      });
      expect(steer).toBeNull();
      assert.strictEqual(queries, 0);
      const plain = yield* loadRestartWakeSteer({
        // A plain error session without the marker is NOT a restart interruption.
        thread: { ...thread, session: {} },
        query: {
          listChildThreadIdsByParent: () => Effect.sync(() => ++queries).pipe(Effect.as([])),
          getThreadShellById: () => Effect.succeed(Option.none()),
        },
      });
      expect(plain).toBeNull();
      assert.strictEqual(queries, 0);
    }),
  );

  it.effect("builds the steer from child shells and honors the cap", () =>
    Effect.gen(function* () {
      const ids = Array.from({ length: RESTART_WAKE_STEER_CHILD_CAP + 3 }, (_, i) => `child-${i}`);
      const steer = yield* loadRestartWakeSteer({
        thread,
        query: {
          listChildThreadIdsByParent: () => Effect.succeed(ids.map((id) => ThreadId.make(id))),
          getThreadShellById: (id) =>
            Effect.succeed(
              Option.some(
                shell({
                  id: ThreadId.make(String(id)),
                  title: String(id),
                  session: {
                    status: "error",
                    lastError: null,
                    stoppedByServerRestart: true,
                  },
                }),
              ),
            ),
        },
      });
      expect(steer).not.toBeNull();
      expect(steer).toContain("stopped on restart");
      expect(steer).toContain("+ 3 more child thread(s) — list them with t3team_children op:list.");
      expect(steer).not.toContain(`child-${RESTART_WAKE_STEER_CHILD_CAP}`);
    }),
  );

  it.effect("degrades to null (never a failed turn) when the query errors", () =>
    Effect.gen(function* () {
      const steer = yield* loadRestartWakeSteer({
        thread,
        query: {
          listChildThreadIdsByParent: () =>
            Effect.fail(new PersistenceDecodeError({ operation: "test", issue: "boom" })),
          getThreadShellById: () => Effect.succeed(Option.none()),
        },
      });
      expect(steer).toBeNull();
    }),
  );
});
