/**
 * Turn-boundary seam of the resource-pressure auto-pause (flag
 * `NEXI_FF_RESOURCE_PRESSURE`), used by the provider command reactor:
 *
 *  - `holdTurn` — asked at every NEW turn start (not replays). While pressure
 *    is critical the turn is held: the reactor queues it in the same per-thread
 *    queue that holds turns during context compaction, so a turn already in
 *    flight finishes and later turn starts line up behind the held one. The
 *    first hold appends a `resource-pressure.paused` activity (the thread's
 *    paused banner derives from it).
 *  - `takeNote` — the turn's context assembly prepends the one pending host
 *    note (escalation or resume) at the same seam as the restart wake steer.
 *  - `runResumes` — replays the held turns of every thread the state machine
 *    resumed, after a `resource-pressure.resumed` activity. Never an error.
 *
 * With the flag off the monitor has no auto-pause and every method is a
 * constant (no Ref, no fiber work).
 *
 * @module t3team-resourcePressureTurnGate
 */
import { CommandId, EventId, ThreadId } from "@t3tools/contracts";
import * as Cause from "effect/Cause";
import * as DateTime from "effect/DateTime";
import * as Effect from "effect/Effect";
import * as Stream from "effect/Stream";

import type { OrchestrationEngineShape } from "./orchestration/Services/OrchestrationEngine.ts";
import { t3teamRandomUUID } from "./t3team-random.ts";
import type { ResourcePressureAutoPauseShape } from "./t3team-resourcePressureAutoPause.ts";

export const RESOURCE_PRESSURE_ACTIVITY_KINDS = {
  paused: "resource-pressure.paused",
  resumed: "resource-pressure.resumed",
} as const;

export const NOTE_HEADER = "[Memory pressure notice — generated by the server, not a user message]";

export interface ResourcePressureTurnGate {
  readonly holdTurn: (threadId: ThreadId) => Effect.Effect<boolean>;
  readonly takeNote: (threadId: ThreadId) => Effect.Effect<string | null>;
  readonly runResumes: <R>(
    replay: (threadId: ThreadId) => Effect.Effect<void, never, R>,
  ) => Effect.Effect<void, never, R>;
}

export const DISABLED_TURN_GATE: ResourcePressureTurnGate = {
  holdTurn: () => Effect.succeed(false),
  takeNote: () => Effect.succeed(null),
  runResumes: () => Effect.void,
};

/** Per-turn host note: the pending pressure note first, then the restart steer, then the message. */
export function composeTurnText(notes: ReadonlyArray<string | null>, messageText: string): string {
  return [...notes.filter((note): note is string => note !== null), messageText].join("\n\n");
}

export function makeResourcePressureTurnGate(input: {
  readonly autoPause: ResourcePressureAutoPauseShape | undefined;
  readonly engine: Pick<OrchestrationEngineShape, "dispatch">;
}): ResourcePressureTurnGate {
  const { autoPause, engine } = input;
  if (autoPause === undefined) return DISABLED_TURN_GATE;

  const appendActivity = (
    threadId: ThreadId,
    kind: (typeof RESOURCE_PRESSURE_ACTIVITY_KINDS)[keyof typeof RESOURCE_PRESSURE_ACTIVITY_KINDS],
    summary: string,
    payload: Record<string, unknown>,
  ) =>
    DateTime.now.pipe(
      Effect.map(DateTime.formatIso),
      Effect.flatMap((createdAt) =>
        engine.dispatch({
          type: "thread.activity.append",
          commandId: CommandId.make(t3teamRandomUUID()),
          threadId,
          activity: {
            id: EventId.make(t3teamRandomUUID()),
            tone: "info",
            kind,
            summary,
            payload,
            turnId: null,
            createdAt,
          },
          createdAt,
        }),
      ),
      // Advisory: a failed activity append must never block or fail a turn.
      Effect.catchCause(() => Effect.void),
    );

  return {
    holdTurn: (threadId) =>
      autoPause.admitTurn(threadId).pipe(
        Effect.tap(({ firstHold }) =>
          firstHold
            ? appendActivity(
                threadId,
                RESOURCE_PRESSURE_ACTIVITY_KINDS.paused,
                "Paused for memory pressure — resumes automatically once pressure clears",
                { reason: "memory-pressure" },
              )
            : Effect.void,
        ),
        Effect.map(({ hold }) => hold),
      ),
    takeNote: (threadId) =>
      autoPause
        .takeTurnNote(threadId)
        .pipe(Effect.map((note) => (note === null ? null : `${NOTE_HEADER}\n${note}`))),
    runResumes: <R>(replay: (threadId: ThreadId) => Effect.Effect<void, never, R>) =>
      autoPause.resumed.pipe(
        Stream.runForEach((batch) =>
          Effect.forEach(
            batch,
            (thread) => {
              const threadId = ThreadId.make(thread.threadId);
              const seconds = Math.round(thread.pausedMs / 1000);
              return appendActivity(
                threadId,
                RESOURCE_PRESSURE_ACTIVITY_KINDS.resumed,
                `Resumed after a ${seconds} s memory-pressure pause`,
                { pausedMs: thread.pausedMs, heldTurnCount: thread.heldTurnCount },
              ).pipe(
                Effect.andThen(replay(threadId)),
                Effect.catchCause((cause) =>
                  Effect.logWarning("resource pressure: held turn replay failed", {
                    threadId,
                    cause: Cause.pretty(cause),
                  }),
                ),
              );
            },
            { discard: true },
          ),
        ),
      ),
  };
}
