/**
 * Regenerate `src/t3team-sdk.workflowReference.generated.ts` from the runtime.
 * Run from packages/t3team-sdk: `node scripts/t3team-generate-workflow-reference.ts`.
 */
import * as NodeFS from "node:fs";
import * as NodeURL from "node:url";

import { generateWorkflowAuthorReference } from "../src/t3team-sdk.workflowReferenceGenerate.ts";

const target = NodeURL.fileURLToPath(
  new URL("../src/t3team-sdk.workflowReference.generated.ts", import.meta.url),
);
const text = generateWorkflowAuthorReference();
NodeFS.writeFileSync(
  target,
  [
    "// GENERATED by scripts/t3team-generate-workflow-reference.ts — do not edit by hand.",
    "// Drift is caught by t3team-sdk.workflowReference.test.ts.",
    "/** The orchestration author reference, generated from the runtime surface. */",
    `export const WORKFLOW_AUTHOR_REFERENCE = ${JSON.stringify(text)};`,
    "",
  ].join("\n"),
);
console.log(`wrote ${target} (${text.length} chars)`);
